config/routes.rb
Rails.application.routes.draw do

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  root to: 'welcome#index'
  resources :categories, only: [:index, :show]
  resources :posts do
    resources :reviews, only: [:new, :create, :destroy]
    resources :favorite_posts, only: [:create, :destroy]
    resources :questions, only: [:new, :create, :destroy]
  end
  resources :users do
    resources :reviews, only: [:new, :create, :destroy]
    resources :favorite_users, only: [:create, :destroy]
  end

  get '/tags/:title' => 'tags#show', as: 'tags'

  resource :sessions, only: [:create]
  

  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  get '/logout' => 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  include Bootsy::Container
  has_secure_password

  has_many :posts, dependent: :destroy
  has_many :reviews, as: :reviewable, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :favorited, source_type: "Post", dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :favorited, source_type: "User", dependent: :destroy
  has_attached_file :avatar, styles: { large: "500x500>", small: "200x200>", thumb: "100x100>" }, default_url: "missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  validates_presence_of :email, :username
  validates :password, :length => {:within => 6..40},:on => :create
  validates :password, :length => {:within => 6..40},allow_nil: true, :on => :update
  validates_uniqueness_of :email, :username
  validates_format_of :password, :with => /^(?=.*[a-zA-Z])(?=.*[0-9]).{6,}$/,:multiline => true ,:on => :create 
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create

  def average_rating
    if self.reviews.length > 0
      ratings = self.reviews
      sum = 0
      ratings.each do |rating|
        sum += rating.score
      end
      return sum / ratings.length
    else
      return 0
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, only: [:show, :edit, :update, :delete]

  def new
    @user = User.new

  end

  def create
    @user = User.new(user_permit)
    if @user.save
      session[:user_id] = @user.id
      redirect_to edit_user_path(@user.id)
    else
      flash[:danger] = @user.errors.full_messages
      redirect_to signup_path
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])
    if @user.update_attributes(update_params)
      redirect_to user_path(@user)
    else
      flash[:danger] = @user.errors.full_messages
      render :'edit'
    end
  end

  def destroy
    user = User.find_by(id: params[:id])
    user.destroy
    session.clear
    redirect_to root_path
  end

  private

  def user_permit
    params.require(:user).permit(:email, :username, :password, :teacher, :avatar)
  end

  def update_params
    params.require(:user).permit(:email, :username, :password, :about, :website, :facebook, :avatar, :experience, :teacher)
  end

end

app/views/users/edit.html.erb
<div class = "container">

  
  <h2>Edit Profile</h2>

  <%= form_for @user, html: { multipart: true } do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
       <h2><%= pluralize(@user.errors.count, "error") %> prohibited this message from being saved:</h2>
       <ul>
         <% @user.errors.full_messages.each do |msg| %>
         <li>
           <%= msg %>
         </li>
         <% end %>
       </ul>
    </div>
  <% end %>

  <div class="row">
    <div id = "email-contact" class="form-group">
      <%=f.label 'Email (required to update account)*', class: "col-xs-12" %>
      <%= f.text_field :email, class: "col-xs-10 col-sm-10 col-md-10" %>
    </div>
  </div>

  <div class="row">
    <div id = "password">
      <%= f.label 'Do you want to teach', class: "col-xs-3"%>
      <%= f.check_box :teacher, class: "col-xs-10 col-sm-10 col-md-10"%>
    </div>
  </div>

  <div class="row">
    <div id = "user-personalization" class="form-group">
      <%= f.label :website, class: "col-xs-12" %>
      <%= f.text_field :website, class: "col-xs-10 col-sm-10 col-md-10" %>
    </div>
  </div>

  <div class="row">
    <div id = "user-facebook" class="form-group">
      <%= f.label :facebook, class: "col-xs-12" %>
      <%= f.text_field :facebook, class: "col-xs-10 col-sm-10 col-md-10" %>
    </div>
  </div>

  <div class="row">
    <div id = "user-about" class="form-group">
      <%= f.label :about, class: "col-xs-12" %>
      <%= f.text_area :about, cols: "15", rows: "10", class: "col-xs-10 col-sm-10 col-md-10" %>
    </div>
  </div>

  <div class="row">
    <div id = "experience">
      <%= f.label :experience, class: "col-xs-10 col-s-10 col-m-10" %>
      <%= f.text_area :experience, cols: "15", rows: "10", class: "col-xs-10 col-sm-10 col-md-10"%>
    </div>
  </div>

  <div class="row">
    <div id = "user-avatar" class="form-group">
      <%= f.file_field :avatar, class: "col-xs-10 col-sm-10 col-md-10" %>
    </div>
  </div>

  <div class="row">
    <div id = "edit-user-submit" class="form-group">
      <%= f.submit %>
    </div>
  </div>

  <% end %>
</div>

app/views/users/new.html.erb
<div class = "container">

  <h2> Welcome new user, please fill out the form below! </h3>

  <%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
       <h2><%= pluralize(@user.errors.count, "error") %> prohibited this message from being saved:</h2>
       <ul>
         <% @user.errors.full_messages.each do |msg| %>
         <li>
           <%= msg %>
         </li>
         <% end %>
       </ul>
    </div>
  <% end %>


  <div class="row">
    <div id = "email">
      <%= f.label 'Email*', class: "col-xs-12" %>
      <%= f.text_field :email, class: "col-xs-9" %>
    </div>
  </div>

  <div class="row">
    <div id = "username">
      <%= f.label 'Username*', class: "col-xs-12" %>
      <%= f.text_field :username, class: "col-xs-9" %>
    </div>
  </div>

  <div class="row">
    <div id = "password">
      <%= f.label 'Password*', class: "col-xs-12"%>
      <%= f.password_field :password , class: "col-xs-9"%>
    </div>
  </div>

  <div class="row">
    <%= f.file_field :avatar %>
  </div

  <div class="row">
    <div id = "submit">
      <%= f.submit 'Signup', class: "btn btn-primary" %>
    </div>
  </div>
  <% end %>

  <p id = "already"> Already have an account? <%= link_to 'Login', login_path %> </p>
</div>

app/views/users/show.html.erb
<div class = "container">
  <div class = "col-xs-6 col-sm-6 col-m-6 pull-right">
    <%= image_tag(@user.avatar.url, id: "user-photo", class: "img-circle img-responsive") %>
  </div>

  <div class = "col-xs-6 col-sm-6 col-md-6">
    <% if current_user == @user %>
      <h1> Welcome <%= @user.username %> </h1>
      <%= link_to 'Edit', edit_user_path(@user.id), class: "btn btn-default" %>
      <%= link_to 'Delete', user_path(@user.id), :method => :delete, :type => "button", class: "btn btn-danger" %>
    <% else %>
      <h1> Meet <%= @user.username %> </h1>
    <% end %>

    <div id = "teacher">
      <% if @user.teacher == true %>
        <h4> Teacher </h4>
      <% else %>
        <h4> Student </h4>
      <% end %>
    </div>

    <% @user.average_rating.times do %>
      <%= image_tag("star.png", size: "20x20") %>
    <% end %></p>
    <h3> Member since: <%= @user.created_at.strftime(" %b. %d, %Y") %> </h3>
    <h4> About: <%= @user.about %> </h4>
    <h4> Experience: <%= @user.experience %> </h4>
    <% if @user.website %>
      <p> Website: <%= link_to @user.website, normalize_url(@user.website) %>  </p>
    <% end %>
    <% if @user.facebook %>
      <p> Facebook: <%= link_to @user.facebook, normalize_url(@user.facebook) %>  </p>
    <% end %>

    <div id="favorites-button">
      <% unless current_user == @user %>
        <% unless current_user.favorite_users.exists?(id: @user.id) %>
          <%= link_to 'Add user to favorites', user_favorite_users_path(user_id: @user), method: :post, class: "btn btn-primary" %>
        <% else %>
          <%= link_to 'Remove from favorites', user_favorite_user_path(user_id:@user.id, favorite_user_id: @user.id), method: :delete, class: "btn btn-default" %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div  id = "profile-tabs" class = "col-xs-12 col-s-12 col-m-12">
    <ul class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active"><a href="#user-post" aria-controls="user-post" role="tab" data-toggle="tab">Posts</a></li>
      <li role="presentation"><a href="#user-reviews" aria-controls="user-reviews" role="tab" data-toggle="tab">Reviews</a></li>
      <li role="presentation"><a href="#favs" aria-controls="favs" role="tab" data-toggle="tab">Favorites</a></li>
    </ul>

    <div class = "tab-content">
      <div role="tabpanel" class="tab-pane fade in active" id="user-post">
        <ol>
          <% @user.posts.each do |post| %>
            <li><h4><%= link_to post.title, post_path(post) %></h4><p>Category: <%= link_to post.category.category_name, category_path(post.category_id) %></p></li>
          <% end %>
        </ol>
      </div>

      <div role="tabpanel" class="tab-pane fade" id="user-reviews">
        <ul>
          <% unless current_user == @user %>
            <p><%= link_to "Add a Review", new_user_review_path(@user) , class: "btn btn-default"  %></p>
          <% end %>
          <% if @user.reviews.exists? %>
            <% @user.reviews.each do |review| %>
              <% if review.reviewer %>
                <li>Rating:
                  <% review.score.times do %>
                    <%= image_tag("star.png", size: "20x20") %>
                  <% end %>  
                </li>

                
                <li>From <%=link_to review.reviewer.username, user_path(review.reviewer) %>
                on <%= review.created_at.strftime("%B %d, %Y") %> <br>
                <%= review.body %>
                <p>
                  <%= link_to "Delete Review", user_review_path(user_id: @user, id: review), method: :delete %></p>
                </li>
              <% end %>
            <% end %>
            <p> This user has no reviews. </p>
          <% end %>
        </ul>
      </div>

      <div role="tabpanel" class="tab-pane fade" id="favs">
        <h4> Favorited Listings: </h4>
        <ul>
          <% @user.favorites.each do |favorite| %>
            <% if favorite.favorited_type == "Post" %>
              <%= link_to favorite.favorited.title, post_path(favorite.favorited_id) %>
            <% end %>
          <% end %>
        </ul>

        <h4> Favorited Users: </h4>
        <ul>
          <% @user.favorites.each do |favorite| %>
            <% if favorite.favorited_type == "User" %>
              <%= link_to favorite.favorited.username, user_path(favorite.favorited_id) %>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>