config/routes.rb
Rails.application.routes.draw do

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  root to: 'welcome#index'
  resources :categories, only: [:index, :show]
  resources :posts do
    resources :reviews, only: [:new, :create, :destroy]
    resources :favorite_posts, only: [:create, :destroy]
    resources :questions, only: [:new, :create, :destroy]
  end
  resources :users do
    resources :reviews, only: [:new, :create, :destroy]
    resources :favorite_users, only: [:create, :destroy]
  end

  get '/tags/:title' => 'tags#show', as: 'tags'

  resource :sessions, only: [:create]
  

  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  get '/logout' => 'sessions#destroy'

end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :category
  belongs_to :user
  has_many :comments
  has_many :reviews, as: :reviewable, dependent: :destroy
  has_many :entry_tags
  has_many :tags, through: :entry_tags
  has_attached_file :photo, styles: { large: "500x500>", small: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

  # def self.get_post_by_trending
  # Post.all.each.sort {|x| x.comments.where("created_at < ?", 5.hours.ago).count}
  # end

  validates :body, length: { minimum: 1000, too_short: "must have at least 250 words" }
  validates_presence_of :title, :body, :tags

  before_save :all_tags


  def self.get_posts_by_newest
    order(created_at: :desc).limit(20)
  end

  def average_rating
    if self.reviews.length > 0
      ratings = self.reviews
      sum = 0
      ratings.each do |rating|
        sum += rating.score
      end
      return sum / ratings.length
    else
      return 0
    end
  end


  def all_tags=(titles)
    self.tags = titles.split(",").map do |title|
      Tag.where(title: title.strip).first_or_create!
    end
  end

  def all_tags
    self.tags.map(&:title).join(", ")
  end

  def posts_with_tag(tag)
    Post.where
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, only: [:new,:create, :edit, :update]

  def index
    @posts = Post.all.paginate(:page => params[:page], :per_page => 15)
  end

  def new 
    @post = Post.new
  end

  def create
    @post = Post.new(post_params.merge(user_id: current_user.id))
    if @post.save
      redirect_to post_path(@post.id)
    else
      flash[:danger] = @post.errors.full_messages
      redirect_to new_post_path
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(update_params)
      redirect_to post_path(@post)
      flash[:success] = "Post updated"
    else
      redirect_to edit_post_path(@post)
      flash[:danger] = @post.errors.full_messages
    end
  end

  def show
    @post = Post.find(params[:id])
    @postcat = Post.all.where(category_id: @post.category.id)
    @find_tag = EntryTag.find_by(post_id: @post)
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :category_id, :all_tags, :photo, :bootsy_image_gallery_id)
  end

  def update_params
    params.require(:post).permit(:title, :body, :category_id, :all_tags, :photo, :bootsy_image_gallery_id)
  end

end

app/views/posts/_post_review.html.erb
<div role="tabpanel" class="tab-pane fade" id="post-reviews">
  <ul id = "previews">
    <% unless current_user == @post.user_id %>
      <p><%= link_to "Add a Review", new_post_review_path(@post), id: "new-review", class: "btn btn-default" %></p>
    <% end %>
    <div id = "reviews-post">
      <% if @post.reviews.exists? %>
        <% @post.reviews.each do |review| %>
          <li>Rating:
            <% review.score.times do %>
            <%= image_tag("star.png", size: "20x20") %>
            <% end %>
          </li>

          <li>From <%=link_to review.reviewer.username, user_path(review.reviewer) %> on <%= review.created_at.strftime("%B %d, %Y") %> <br>
            <%= review.body %>
              <% if current_user %>
            <p> <% if review.user_id == current_user.id %>
                  <%= link_to "Delete Review", post_review_path(post_id: @post, id: review), method: :delete %></p>
                <% end %>
              <% end %>
          </li>
        <% end %>
      <% else %>
          <p> This post has no reviews. </p>
      <% end %>
    </div>
  </ul>
</div>

app/views/posts/_review.html.erb
<div id = "new-review-form">
  <%= form_for [@reviewable, @review] do |f| %>

    <div class = "row">
      <div id = "review-body">
        <%= f.label 'Review', class: "col-xs-12" %>
        <%= f.text_area :body,cols: "10", rows: "5", class: "col-xs-6" %>
      </div>
    </div> 

    <div class  = "row">
      <div id = "review-score">
        <%= f.label 'Score', class: "col-xs-12" %>
        <%= f.select :score, [1,2,3,4,5], class: "col-xs-9" %>
      </div>
    </div>

    <div class = "row"
      <div id = "submit-button">
        <%= f.submit %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<div class = "container">

  <% if @post.errors.any?  %>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
        <li> <%= "#{msg}" %></li>
    <% end %>
    </ul>
  <% end %>

  <h3> Edit post </h3>

  <div id = "edit-post">
    <%= form_for @post do |f| %>
      <div class="row">
        <div class="form-group">
          <%= f.label 'What are you teaching about today?*', class: "col-xs-8"%>
          <%= f.text_field :title, class: "col-xs-10 col-sm-10 col-md-10" %>
        </div>
      </div>

      <div class="row">
        <div class="form-group">
          <%= f.label 'Edit body', class: "col-xs-12"  %>
          <%= f.bootsy_area :body, cols: "140", rows: "60", id: "field", class: "col-xs-10 col-sm-10 col-md-10"%>
        </div>
      </div>

      <div class="row">
        <div class="form-group">
          <%= f.label 'Tags (separated by commas and NO spaces, please!!)', class: "col-xs-8"%>
          <%= f.text_field :all_tags, class: "col-xs-10 col-sm-10 col-md-10" %>
        </div>
      </div>

      <div class="row">
      <%= f.file_field :photo %>
      </div>

      <div class="row">
        <div class="form-group">
        <%= f.label :category, class: "col-xs-12" %>
        <%= f.collection_select(:category_id, Category.all, :id, :category_name, class: "col-xs-10 col-sm-10 col-md-10") %>
        </div>
      </div>

      <div class="row">
        <div class="form-group">
        <%= f.submit :submit, class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>

  <div class = "col-xs-12 col-s-12 col-md-12">
    <h3 id = "guidelines">Guidelines:</h3>
      <li id = "guides"> Keep your language simple and easy to understand -- if you wouldn't write or say it to a friend, its probably best not to say it to our users. </li>
      <li id = "guides"> No cursing, swearing. No hateful or discriminatory languages. </li>
      <li id = "guides"> Don't write about anything you don't know about. Our users trust us to screen our teachers.</li>
      <li id = "guides"> Keep it fun!</li>
      <li id = "guides"> All posts are moderated and will be removed if they violate the guidelines.</li>
  </div>
</div>

app/views/posts/index.html.erb
<header class="business-header">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h1 id = "tagline">Explore all posts</h1>
      </div>
    </div>
  </div>
</header>

<div class = "container">
  <div class="row">
    <div class = "all-posts">
      <% @posts.each do |post| %>
        <div class=" col-xs-6 col-s-10 col-md-4 portfolio-item">
          <li><%= link_to image_tag(post.photo.url, size: "350x200", :class => "img-circle"), post_path(post.id) %> 
            <h3><%= link_to post.title, post_path(post.id), class: "link-post" %></h3></li>
        </div>
      <% end %>
    </div>
  </div>
  
  <div class="pagination">
    <div class="page_info">
      <%= page_entries_info @posts %>
    </div>
    <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
  </div>
</div>

app/views/posts/new.html.erb
<div class = "container">
  <% if current_user.teacher == true %>
    <% if @post.errors.any?  %>
      <ul>
      <% @post.errors.full_messages.each do |msg| %>
          <li> <%= "#{msg}" %></li>
      <% end %>
      </ul>
    <% end %>


    <div class = "col-xs-12 col-s-12 col-md-12">
      <div id = "post-instr">
        <h2 id = "new-post-info"> We're so glad you want to share your knowledge! Please follow the guidelines while filling out the form below! </h2>

        <h3 id = "guidelines">Guidelines:</h3>

          <li id = "guides"> Keep your language simple and easy to understand -- if you wouldn't write or say it to a friend, its probably best not to say it to our users. </li>
          <li id = "guides"> No cursing, swearing. No hateful or discriminatory languages. </li>
          <li id = "guides"> Don't write about anything you don't know about. Our users trust us to screen our teachers.</li>
          <li id = "guides"> Keep it fun!</li>
          <li id = "guides"> All boxes with '*' are required!</li>
          <li id = "guides"> All posts are moderated and will be removed if they violate the guidelines.</li>
      </div>
    </div>


    <div id = "new-post">
      <%= form_for @post do |f| %>
      <div class="row">
        <div class="form-group">
          <%= f.label 'What are you teaching about today?*', class: "col-xs-7"%>
          <%= f.text_field :title, class: "col-xs-10 col-sm-10 col-md-10" %>
        </div>
      </div>

      <div class="row">
        <div class="form-group">
          <%= f.label "*", class: "col-xs-12" %><br>
          <%= f.bootsy_area :body, cols: "120", rows: "30", id: "field", class: "col-xs-12 col-sm-12 col-md-12" %>
        </div>
      </div>

      <div class="row">
        <div class="form-group">
          <%= f.label 'Tags (separated by commas and NO spaces, please!!)*', class: "col-xs-12"%>
          <%= f.text_field :all_tags, class: "col-xs-10 col-sm-10 col-md-10" %>
        </div>
      </div>

      <div class="row">
        <%= f.label 'Please upload a cover photo for your post.', class: "col-xs-12" %>
        <%= f.file_field :photo, class: "jumbo-photo col-xs-10 col-sm-10 col-md-10" %>
      </div>

      <div class="row">
        <div class="form-group">
        <%= f.label 'Which category does your post belong in?*', class: "col-xs-12" %>
        <%= f.collection_select(:category_id, Category.all, :id, :category_name, class: "col-xs-10 col-sm-10 col-md-10") %>
        </div>
      </div>

      <div class="row">
        <div class="form-group">
        <%= f.submit 'Create Post', class: "btn btn-primary" %>
        </div>
      </div>
      <% end %>
    </div>

  <% else %>
    <h1> We're so glad your interested in posting, however, you MUST be a 'teacher' to submit! <%= link_to 'Edit your status to become a teacher!', edit_user_path(current_user.id) %>
  <% end %>
</div>

app/views/posts/show.html.erb
<header class="posts-header" style = "background-image: url(<%= @post.photo.url %>)">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="transbox">
          <h1> <%= @post.title.upcase %> </h1>
          <p class = "post-author"> By <%= link_to @post.user.username.upcase, user_path(@post.user_id) %> </p>
          <p class = "post-time"> <%= @post.created_at.strftime(" %b. %d, %Y") %></p>
           <p><% @post.average_rating.times do %>
              <%= image_tag("star.png", size: "40x40", id: "review-stars", class: "img-rounded img-responsive") %>
            <% end %></p>
        </div>

        <div class = "col-xs-offet-5 col-s-offet-5 col-md-offset-5">
          <div id = "post-buttons">
            <div class = "btn-larg" id = "edit">
              <% if current_user %>
                <% if current_user.id == @post.user_id %>
                  <%= link_to 'Edit post', edit_post_path(@post), class: "btn btn-primary" %>
                <% end %>
              <% end %>
            </div>

            <div class = "btn-lrg" id="favorites">
              <% if current_user %>
                <% if current_user != @post.user_id %>
                  <% unless current_user.favorite_posts.exists?(id: @post.id) %>
                    <%= link_to 'Add post to favorites', post_favorite_posts_path(post_id: @post), method: :post, class: "btn btn-primary" %>
                  <% else %>
                    <%= link_to 'Remove Favorite', post_favorite_post_path(post_id:@post.id, favorite_post_id: @post.id), method: :delete, class: "btn btn-default" %>
                  <% end %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

<div class = "container" id = "show-post">

  <div class = "col-xs-12 col-sm-12 col-m-12">
    <div id = "post-body">
       <%= @post.body.html_safe  %>
    </div>

    <div id = "post-tags">
      Tags : <% @post.tags.map do |tag| %>
      <%= link_to tag.title, tags_path(tag.title), class: "index-post-link" %>, 
      <% end %>
    </div>
  </div>

  <div id="profile-content" class="col-xs-12 col-s-12 col-md-12">
    <ul class = "nav nav-tabs" role = "tablist">
      <li role="presentation" class="active"><a href="#post-post" aria-controls="post-post" role="tab" data-toggle="tab"> Posts in <%= @post.category.category_name %></a></li>
      <li role="presentation"><a href="#post-reviews" aria-controls="post-reviews" role="tab" data-toggle="tab">Reviews (<%= @post.reviews.count %>)</a></li>
    </ul>


    <div class = "tab-content">
      <div role="tabpanel" class="tab-pane fade in active" id="post-post">
        <div class = "row">
          <% @postcat.each do |post| %>
            <div class=" col-xs-12 col-s-6 col-md-4 portfolio-item">
              <li class = "crop"><p><%= link_to image_tag(post.photo.url, size: "350x200", :class => "img-circle "), post_path(post.id) %> </p>
                <p><p><%= link_to post.title, post_path(post.id), class: "link-post" %></p></p>
              </li>
            </div>
          <% end %>
        </div>
      </div>
      <%= render "post_review", locals:{post:@post}%>      
    </div>
  </div
</div>