config/routes.rb
Rails.application.routes.draw do

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  root to: 'welcome#index'
  resources :categories, only: [:index, :show]
  resources :posts do
    resources :reviews, only: [:new, :create, :destroy]
    resources :favorite_posts, only: [:create, :destroy]
    resources :questions, only: [:new, :create, :destroy]
  end
  resources :users do
    resources :reviews, only: [:new, :create, :destroy]
    resources :favorite_users, only: [:create, :destroy]
  end

  get '/tags/:title' => 'tags#show', as: 'tags'

  resource :sessions, only: [:create]
  

  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  get '/logout' => 'sessions#destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TeachMeSomething</title>
  <meta name=viewport content="width=device-width,initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <link href='https://fonts.googleapis.com/css?family=Playfair+Display:400,700' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
  <link rel="icon" href="/favicon.ico" type="image/x-icon">
  <%= csrf_meta_tags %>

  


  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-74064267-1', 'auto');
    ga('send', 'pageview');

  </script>
</head>
<body>
  <!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-TND54Z"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-TND54Z');</script>
<!-- End Google Tag Manager -->



<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Teach Me Something', root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'All Posts', posts_path %></li>
        <li><%= link_to 'New Post', new_post_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><% @categories.each do |category| %>
                <%= link_to category.category_name, category_path(category) %>
                <% end %>
            </li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Tags <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><% @tags.each do |tag| %>
                <%= link_to tag.title, tags_path(tag.title) %>
                <% end %></li>
          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to "Welcome #{current_user.username}", user_path(current_user.id) if current_user %></li>
          <li><%= link_to 'Sign out', logout_path %></li>
        <% else %>
        <li><%= link_to "Login", login_path %></li>
          <li><%= link_to "Sign up", signup_path %></li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %>">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>


  
<%= yield %>


</body>
</html>